# DATA: npcpd2_merged.ttl,bao_vocabulary_assay.owl
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bioassay: <http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/>
PREFIX bao: <http://www.bioassayontology.org/bao#>
PREFIX oidd_assay: <http://openinnovation.lilly.com/bioassay#>
PREFIX ncgc_substance: <http://ncats.nih.gov/ncgc/substance#>
PREFIX opddr: <http://rdf.ncats.nih.gov/opddr/>
PREFIX ncats_sample: <http://rdf.ncats.nih.gov/ncgc/sample/>

SELECT
  ?substance ?oidd ?bioassay ?assayname
WHERE
{
  ?substance opddr:activeInAssay ?oidd .
  ?oidd skos:exactMatch ?bioassay .
  ?oidd rdfs:label ?assayname .
  FILTER(REGEX(?assayname, "Basal_Viability","i"))
}
ORDER BY ?substance
